In [1]:
#numpy

In [3]:
# Creation of Arrays
import numpy as np
arr = np.array([1, 2, 3])
print(arr)
arr = np.array([[1, 2, 3],[4, 5, 6]])
print( arr)
# Creating an array from tuple
arr = np.array((1, 3, 2))
print( arr)


[1 2 3]
[[1 2 3]
 [4 5 6]]
[1 3 2]


In [4]:
# indexing in numpy array
import numpy as np
# Initial Array
arr = np.array([[-1, 2, 0, 4],
				[4, -0.5, 6, 0],
				[2.6, 0, 7, 8],
				[3, -7, 4, 2.0]])
print("Initial Array: ")
print(arr)
# with the use of slicing method
sliced_arr = arr[:2, ::2]
print ("Array with first 2 rows and"
	" alternate columns(0 and 2):\n", sliced_arr)
# specific Indices
Index_arr = arr[[1, 1, 0, 3], 
				[3, 2, 1, 0]]
print ("\nElements at indices (1, 3), "
	"(1, 2), (0, 1), (3, 0):\n", Index_arr)


Initial Array: 
[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]
Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (1, 3), (1, 2), (0, 1), (3, 0):
 [0. 6. 2. 3.]


In [5]:
# Python program to demonstrate sorting in numpy 
import numpy as np 

a = np.array([[1, 4, 2], 
				[3, 4, 6], 
			[0, -1, 5]]) 

# sorted array 
print ("Array elements in sorted order:\n", 
					np.sort(a, axis = None)) 

# sort array row-wise 
print ("Row-wise sorted array:\n", 
				np.sort(a, axis = 1)) 

# specify sort algorithm 
print ("Column wise sort by applying merge-sort:\n", 
			np.sort(a, axis = 0, kind = 'mergesort')) 

# Example to show sorting of structured array 
# set alias names for dtypes 
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)] 

# Values to be put in array 
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7), 
		('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)] 
			
# Creating array 
arr = np.array(values, dtype = dtypes) 
print ("\nArray sorted by names:\n", 
			np.sort(arr, order = 'name')) 
			
print ("Array sorted by grauation year and then cgpa:\n", 
				np.sort(arr, order = ['grad_year', 'cgpa'])) 


Array elements in sorted order:
 [-1  0  1  2  3  4  4  5  6]
Row-wise sorted array:
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]
Column wise sort by applying merge-sort:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]

Array sorted by names:
 [(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
Array sorted by grauation year and then cgpa:
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]
